import type { BonusConfig } from "../src/lib/types";

export const FINAL_RA_ACCOUNTS = [
  { name: "Mikhael", email: "e1354426@u.nus.edu" },
  { name: "Jovin", email: "e1249335@u.nus.edu" },
  { name: "Rutu", email: "rutuparna.kulkarni@u.nus.edu" },
  { name: "Averil", email: "e1356625@u.nus.edu" },
  { name: "Roxanne", email: "roxannetyx@u.nus.edu" },
  { name: "Aviel", email: "e0540330@u.nus.edu" },
  { name: "Audric", email: "e1398128@u.nus.edu" },
  { name: "Miral", email: "e1124969@u.nus.edu" },
  { name: "Jun Xiang", email: "e1384355@u.nus.edu" },
  { name: "Maahir", email: "maahirrgarg@u.nus.edu" },
] as const;

export const SHARED_ADMIN_EMAIL = "ra@pgpals.admin";
export const SHARED_ADMIN_NAME = "PGPals RA Admin";

export interface FinalTask {
  week: 1 | 2;
  number: number;
  category: string;
  title: string;
  description: string;
  points: number;
  startDate: string;
  endDate: string;
  type: "standard" | "pair";
  pairTeamCount: number;
  bonusConfig: BonusConfig | null;
}

interface TaskInput {
  week: 1 | 2;
  number: number;
  category: string;
  title: string;
  instructions: string;
  proof: string;
  points: number;
  startDate: string;
  endDate: string;
  groupTeams?: number;
  note?: string;
  bonusConfig?: BonusConfig;
}

function task(input: TaskInput): FinalTask {
  const note = input.note ? `\n\n${input.note}` : "";
  return {
    week: input.week,
    number: input.number,
    category: input.category,
    title: input.title,
    description:
      `**Week ${input.week} · ${input.category} · Challenge ${input.number}**\n\n` +
      `${input.instructions}\n\n**Proof:** ${input.proof}${note}`,
    points: input.points,
    startDate: input.startDate,
    endDate: input.endDate,
    type: input.groupTeams ? "pair" : "standard",
    pairTeamCount: input.groupTeams ?? 2,
    bonusConfig: input.bonusConfig ?? null,
  };
}

export const FINAL_TASKS: FinalTask[] = [
  task({
    week: 1,
    number: 1,
    category: "Creative",
    title: "Create a Team Name & Catchphrase",
    instructions: "Choose a team name and create a short catchphrase that represents both partners.",
    proof: "Submit one photo of both partners and include the team name and catchphrase in the caption.",
    points: 10,
    startDate: "2026-08-31",
    endDate: "2026-08-31",
  }),
  task({
    week: 1,
    number: 2,
    category: "Creative",
    title: "Draw Portraits of Each Other",
    instructions: "Each partner draws the other. Style and skill level do not matter; have fun with it.",
    proof: "Submit a clear photo showing both partners holding both finished portraits.",
    points: 10,
    startDate: "2026-08-31",
    endDate: "2026-09-02",
  }),
  task({
    week: 1,
    number: 3,
    category: "Creative",
    title: "Recreate an Iconic Movie Poster",
    instructions: "Pick a recognisable movie poster and recreate it together using safe props and locations available to you.",
    proof: "Submit your recreation and, if helpful, a screenshot of the original poster for comparison.",
    points: 10,
    startDate: "2026-08-31",
    endDate: "2026-09-02",
  }),
  task({
    week: 1,
    number: 4,
    category: "Creative",
    title: "Film a TikTok Challenge or Instagram Story",
    instructions: "Create a TikTok-style challenge video or Instagram Story with your partner and tag the official PGPR Instagram account.",
    proof: "Submit the video (maximum 60 seconds) plus a screenshot showing the published story/post and tag.",
    points: 20,
    startDate: "2026-09-01",
    endDate: "2026-09-03",
  }),
  task({
    week: 1,
    number: 5,
    category: "Creative",
    title: "Design Your Dream PGPR Room",
    instructions: "Work together to draw your ideal PGPR room, including at least three features you would add or change.",
    proof: "Submit a clear photo of both partners with the completed design.",
    points: 10,
    startDate: "2026-09-02",
    endDate: "2026-09-04",
  }),
  task({
    week: 1,
    number: 6,
    category: "Creative",
    title: "Make Shadow Puppets",
    instructions: "Create a short shadow-puppet scene together using a light source and your hands or safe paper cut-outs.",
    proof: "Submit a photo or short video showing both partners' shadow-puppet scene.",
    points: 10,
    startDate: "2026-08-31",
    endDate: "2026-09-01",
  }),
  task({
    week: 1,
    number: 7,
    category: "Creative",
    title: "Find the Letters P-G-P-R",
    instructions: "Find four different objects whose names begin with P, G, P, and R, then arrange them in that order.",
    proof: "Submit one photo showing all four objects in P-G-P-R order and both partners.",
    points: 10,
    startDate: "2026-09-01",
    endDate: "2026-09-03",
  }),
  task({
    week: 1,
    number: 8,
    category: "Creative",
    title: "Create a Five-Move Secret Handshake",
    instructions: "Invent and learn a secret handshake containing at least five distinct moves.",
    proof: "Submit one continuous video, no longer than 60 seconds, showing the complete handshake.",
    points: 10,
    startDate: "2026-09-02",
    endDate: "2026-09-05",
  }),
  task({
    week: 1,
    number: 9,
    category: "Creative",
    title: "Recreate an Emoji With Your Faces",
    instructions: "Choose one emoji at random and recreate its expression or pose together.",
    proof: "Submit a photo of your recreation and include the chosen emoji in the caption.",
    points: 10,
    startDate: "2026-08-31",
    endDate: "2026-09-01",
  }),
  task({
    week: 1,
    number: 10,
    category: "Creative",
    title: "Tackle a Tongue Twister Together",
    instructions: "Choose any tongue twister and record both partners attempting it clearly.",
    proof: "Submit a video no longer than 60 seconds in which both partners speak.",
    points: 20,
    startDate: "2026-09-02",
    endDate: "2026-09-03",
  }),
  task({
    week: 1,
    number: 11,
    category: "Creative",
    title: "Strike the Warrior III Pose",
    instructions: "Both partners attempt the yoga Warrior III pose in a safe, open space. Modify the pose if needed and do not risk a fall.",
    proof: "Submit a photo showing both partners attempting the pose at the same time.",
    points: 10,
    startDate: "2026-09-01",
    endDate: "2026-09-01",
  }),
  task({
    week: 1,
    number: 12,
    category: "Creative",
    title: "Learn and Perform a Magic Trick",
    instructions: "Learn one simple, safe magic trick and perform it for your partner or together.",
    proof: "Submit a continuous video, no longer than 60 seconds, showing the trick being performed.",
    points: 10,
    startDate: "2026-09-03",
    endDate: "2026-09-06",
  }),
  task({
    week: 1,
    number: 13,
    category: "Creative",
    title: "Film a 30-Second MasterChef Episode",
    instructions: "Create a playful 30-second MasterChef-style episode featuring both partners and any food or drink.",
    proof: "Submit the finished video; keep it at or under 30 seconds.",
    points: 30,
    startDate: "2026-09-04",
    endDate: "2026-09-06",
  }),
  task({
    week: 1,
    number: 14,
    category: "Explore",
    title: "Visit Every NUS Library",
    instructions: "Visit every NUS Libraries location that is open and publicly accessible during the challenge window. Respect quiet zones and each library's photography rules.",
    proof: "Submit a collage or up to five attachments that collectively identify every visited library and show both partners at each location.",
    points: 40,
    startDate: "2026-09-02",
    endDate: "2026-09-06",
  }),
  task({
    week: 1,
    number: 15,
    category: "Explore",
    title: "Visit the Playground Near Block 14",
    instructions: "Find the children's playground near PGPR Block 14 and visit it together without disrupting other users.",
    proof: "Submit a photo of both partners with the playground clearly visible.",
    points: 10,
    startDate: "2026-08-31",
    endDate: "2026-09-02",
  }),
  task({
    week: 1,
    number: 16,
    category: "Explore",
    title: "Capture a Singapore Flyer Photo",
    instructions: "Travel together to a safe public viewpoint near the Singapore Flyer and compose an Instagram-worthy shot.",
    proof: "Submit a photo showing both partners and the Singapore Flyer.",
    points: 30,
    startDate: "2026-09-04",
    endDate: "2026-09-06",
  }),
  task({
    week: 1,
    number: 17,
    category: "Explore",
    title: "Visit Five Faculty Signboards",
    instructions: "Explore campus and find signboards for five different NUS faculties or schools.",
    proof: "Submit photos or a collage showing both partners with all five clearly readable signboards.",
    points: 20,
    startDate: "2026-09-02",
    endDate: "2026-09-05",
  }),
  task({
    week: 1,
    number: 18,
    category: "Explore",
    title: "Ride to the NUS Bukit Timah Campus",
    instructions: "Use the NUS P bus service to visit the Bukit Timah Campus together. Follow all transport and campus-access rules.",
    proof: "Submit a photo of both partners at a recognisable Bukit Timah Campus sign or landmark and proof of the P-bus journey.",
    points: 50,
    startDate: "2026-09-04",
    endDate: "2026-09-06",
  }),
  task({
    week: 1,
    number: 19,
    category: "Explore",
    title: "Ride Three NUS Shuttle Routes",
    instructions: "Ride at least three different NUS shuttle-bus routes together, following normal passenger rules.",
    proof: "Submit photos or screenshots that identify the three route names and show both partners during the journey.",
    points: 30,
    startDate: "2026-09-01",
    endDate: "2026-09-04",
  }),
  task({
    week: 1,
    number: 20,
    category: "Explore",
    title: "Find Four Languages on a Sign",
    instructions: "Find a sign that displays four different languages, or a set of nearby signs that collectively displays four languages.",
    proof: "Submit a photo or collage in which the four languages are readable and both partners are visible.",
    points: 10,
    startDate: "2026-09-02",
    endDate: "2026-09-04",
  }),
  task({
    week: 1,
    number: 21,
    category: "Food",
    title: "Share a Meal at Supper Stretch",
    instructions: "Have a meal together at Supper Stretch and try to learn one new thing about your partner while you eat.",
    proof: "Submit a photo showing both partners, the meal, and a recognisable part of the location.",
    points: 20,
    startDate: "2026-09-03",
    endDate: "2026-09-06",
  }),
  task({
    week: 1,
    number: 22,
    category: "Food",
    title: "Make Breakfast Together",
    instructions: "Prepare a breakfast together. Keep food handling and any cooking equipment safe.",
    proof: "Submit a photo of both partners with the finished breakfast, plus an optional preparation photo.",
    points: 30,
    startDate: "2026-08-31",
    endDate: "2026-09-03",
  }),
  task({
    week: 1,
    number: 23,
    category: "Food",
    title: "Eat at Frontier Canteen",
    instructions: "Visit Frontier Canteen and share a meal there with your partner.",
    proof: "Submit a photo showing both partners, the food, and the location.",
    points: 20,
    startDate: "2026-09-02",
    endDate: "2026-09-05",
  }),
  task({
    week: 1,
    number: 24,
    category: "Food",
    title: "Split and Review a Dessert",
    instructions: "Choose one dessert to share, then agree on a rating and a short review.",
    proof: "Submit a photo of both partners with the dessert and put your rating and review in the caption.",
    points: 10,
    startDate: "2026-09-02",
    endDate: "2026-09-04",
  }),
  task({
    week: 1,
    number: 25,
    category: "Food",
    title: "Film a PGPR Canteen Food Review",
    instructions: "Buy any meal from the PGPR canteen and film a joint food review of about one minute.",
    proof: "Submit a video at or under 60 seconds showing both partners, the meal, and your review.",
    points: 20,
    startDate: "2026-09-04",
    endDate: "2026-09-06",
  }),
  task({
    week: 1,
    number: 26,
    category: "F&S",
    title: "Sort Recyclables Into Two Bin Types",
    instructions: "Identify clean recyclable items and correctly place them into at least two of the three recycling-bin types. Do not remove waste from bins or handle unsafe items.",
    proof: "Submit one short video showing both partners and the two correct disposal actions.",
    points: 10,
    startDate: "2026-08-31",
    endDate: "2026-09-02",
  }),
  task({
    week: 1,
    number: 27,
    category: "Sports & Exercise",
    title: "Visit the PGP Gym",
    instructions: "Visit the PGP gym together during its permitted hours. You do not need to photograph other gym users or perform any risky exercise.",
    proof: "Submit a photo of both partners at the gym entrance or another permitted gym location.",
    points: 10,
    startDate: "2026-09-02",
    endDate: "2026-09-04",
  }),
  task({
    week: 1,
    number: 28,
    category: "Sports & Exercise",
    title: "Attend a PGPR or NUS Sports Interest Group",
    instructions: "Attend one official PGPR or NUS sports interest-group session together and participate respectfully.",
    proof: "Submit a photo of both partners with the session signage, organiser, or activity; get consent before including others.",
    points: 40,
    startDate: "2026-08-31",
    endDate: "2026-09-06",
  }),
  task({
    week: 1,
    number: 29,
    category: "Sports & Exercise",
    title: "Reach 30,000 Combined Steps in One Day",
    instructions: "On one calendar day, record a combined total of at least 30,000 steps across both partners. Walk safely and stop if either partner feels unwell.",
    proof: "Submit same-day screenshots from both step trackers with the date and totals visible; the two totals must add up to at least 30,000.",
    points: 20,
    startDate: "2026-09-01",
    endDate: "2026-09-06",
  }),
  task({
    week: 1,
    number: 30,
    category: "Sports & Exercise",
    title: "Score a Basketball Shot Each",
    instructions: "At a proper basketball court, keep trying until both partners score one basket.",
    proof: "Submit one continuous video showing each partner successfully making a shot.",
    points: 20,
    startDate: "2026-09-03",
    endDate: "2026-09-05",
  }),
  task({
    week: 1,
    number: 31,
    category: "Leisure",
    title: "Film the Waves at West Coast Park",
    instructions: "Visit West Coast Park together and create a short cinematic video of the waves from a safe, permitted area.",
    proof: "Submit a video no longer than 60 seconds that includes the waves and both partners.",
    points: 20,
    startDate: "2026-09-04",
    endDate: "2026-09-06",
  }),
  task({
    week: 1,
    number: 32,
    category: "Leisure",
    title: "Follow the PGPR TikTok and Instagram Accounts",
    instructions: "Both partners follow the official PGPR TikTok and Instagram accounts.",
    proof: "Submit screenshots showing the follow status for both partners on both platforms; account handles may be obscured if privacy requires it.",
    points: 10,
    startDate: "2026-08-31",
    endDate: "2026-08-31",
  }),
  task({
    week: 1,
    number: 33,
    category: "Leisure",
    title: "Take a Photo With Two Cluster Leaders",
    instructions: "Meet two PGPR Cluster Leaders with your partner and ask politely for a group photo.",
    proof: "Submit a photo showing both partners and both consenting Cluster Leaders.",
    points: 10,
    startDate: "2026-08-31",
    endDate: "2026-09-03",
  }),
  task({
    week: 1,
    number: 34,
    category: "Leisure",
    title: "Take a Photo With Five RAs",
    instructions: "Meet five different PGPR RAs with your partner and ask each person before taking a photo.",
    proof: "Submit a collage or up to five photos that collectively show both partners with five consenting RAs.",
    points: 20,
    startDate: "2026-08-31",
    endDate: "2026-09-06",
  }),
  task({
    week: 1,
    number: 35,
    category: "Leisure",
    title: "Learn to Moonwalk",
    instructions: "Practise the moonwalk together in a clear, non-slip space until both partners can demonstrate it.",
    proof: "Submit a short video showing both partners attempting the moonwalk.",
    points: 10,
    startDate: "2026-09-03",
    endDate: "2026-09-05",
  }),
  task({
    week: 1,
    number: 36,
    category: "Leisure",
    title: "Juggle for 10 Seconds",
    instructions: "Learn to juggle safe, lightweight objects continuously for at least 10 seconds. Either partner may perform while the other supports.",
    proof: "Submit one continuous video clearly showing at least 10 seconds of juggling and both partners.",
    points: 10,
    startDate: "2026-09-03",
    endDate: "2026-09-06",
  }),
  task({
    week: 1,
    number: 37,
    category: "Leisure",
    title: "Beatbox for 15 Seconds",
    instructions: "Create and perform a beatbox routine lasting at least 15 seconds, with both partners contributing.",
    proof: "Submit one continuous video showing the full routine.",
    points: 10,
    startDate: "2026-09-02",
    endDate: "2026-09-04",
  }),
  task({
    week: 1,
    number: 38,
    category: "Leisure",
    title: "Wear Matching Colours",
    instructions: "Coordinate outfits so both partners visibly wear the same main colour.",
    proof: "Submit one full or half-body photo showing both partners and the matching colour.",
    points: 10,
    startDate: "2026-08-31",
    endDate: "2026-09-02",
  }),
  task({
    week: 1,
    number: 39,
    category: "Leisure",
    title: "Build the PGPals Finale Playlist",
    instructions: "Create a Spotify playlist together that would work well at the PGPals finale. Keep the selections event-appropriate.",
    proof: "Submit a screenshot of the playlist showing its title and tracks, and include a share link in the caption.",
    note: "**Judged bonus:** RAs will select one winning playlist for **50 bonus PGP Coins**. This is awarded manually after judging, not automatically on approval.",
    points: 20,
    startDate: "2026-08-31",
    endDate: "2026-09-06",
  }),
  task({
    week: 1,
    number: 40,
    category: "Leisure",
    title: "Sing Together at the Shuttle-Bus Stop",
    instructions: "While waiting safely at a shuttle-bus stop, sing quietly together without disturbing other passengers.",
    proof: "Submit a short video showing both partners and enough of the stop to identify the setting.",
    points: 20,
    startDate: "2026-09-02",
    endDate: "2026-09-05",
  }),
  task({
    week: 1,
    number: 41,
    category: "Multi-pair",
    title: "Picnic at UTown Green With Another Team",
    instructions: "Form a two-team group and have a picnic together at NUS UTown Green. Leave the area clean when you finish.",
    proof: "Submit one shared photo showing all four residents, the picnic, and UTown Green.",
    points: 30,
    startDate: "2026-09-03",
    endDate: "2026-09-06",
    groupTeams: 2,
  }),
  task({
    week: 1,
    number: 42,
    category: "Multi-pair",
    title: "Lounge Bonding With Three Teams",
    instructions: "Form a three-team group and spend time bonding in any PGP lounge through cards, a movie, conversation, or another shared activity.",
    proof: "Submit a shared photo or short video showing all six residents, the activity, and the lounge setting.",
    points: 30,
    startDate: "2026-09-04",
    endDate: "2026-09-06",
    groupTeams: 3,
  }),
  task({
    week: 1,
    number: 43,
    category: "Multi-pair",
    title: "Exchange Snacks From Home",
    instructions: "Form a two-team group. Each team brings a snack connected to a partner's home country or culture, then exchange and try them together. Check dietary restrictions first.",
    proof: "Submit one shared photo showing all four residents and the snacks, with the snack origins named in the caption.",
    points: 30,
    startDate: "2026-09-05",
    endDate: "2026-09-06",
    groupTeams: 2,
  }),
  task({
    week: 1,
    number: 44,
    category: "Multi-pair",
    title: "Eat at Al Amaan With Another Team",
    instructions: "Form a two-team group and share a meal at Al Amaan near NUS.",
    proof: "Submit one shared photo showing all four residents, the meal, and the location.",
    points: 20,
    startDate: "2026-09-04",
    endDate: "2026-09-06",
    groupTeams: 2,
  }),
  task({
    week: 1,
    number: 45,
    category: "Multi-pair",
    title: "Spell PGPR With Your Bodies",
    instructions: "Form a two-team group and use all four residents' bodies to create the letters P-G-P-R in a single composition or four-frame collage.",
    proof: "Submit one shared photo or collage in which all four letters and all four residents are visible.",
    points: 30,
    startDate: "2026-09-05",
    endDate: "2026-09-06",
    groupTeams: 2,
  }),
  task({
    week: 1,
    number: 46,
    category: "Pokémon",
    title: "Spot Five Animal Species on Campus",
    instructions: "Find five different animal species on campus, such as a cat, bird, squirrel, insect, or fish. Observe from a respectful distance and do not feed or disturb wildlife.",
    proof: "Submit a collage or up to five photos identifying all five species; include both partners in at least one attachment.",
    points: 30,
    startDate: "2026-08-31",
    endDate: "2026-09-06",
  }),
  task({
    week: 1,
    number: 47,
    category: "Pokémon",
    title: "Find a Giant Fallen Leaf",
    instructions: "Find a fallen leaf that is larger than both partners' hands placed side by side. Do not pluck leaves from living plants.",
    proof: "Submit a photo showing the leaf, both partners, and both hands beside it for scale.",
    points: 10,
    startDate: "2026-09-01",
    endDate: "2026-09-03",
  }),
  task({
    week: 1,
    number: 48,
    category: "Pokémon",
    title: "Find a Shape in the Clouds",
    instructions: "Find a cloud that looks like an object, animal, or character and agree on what you see.",
    proof: "Submit a photo including the cloud and both partners, and name the shape in the caption.",
    points: 20,
    startDate: "2026-08-31",
    endDate: "2026-09-02",
  }),
  task({
    week: 1,
    number: 49,
    category: "Pokémon",
    title: "Find Something Older Than Both of You",
    instructions: "Find an object, building, artwork, or tree that is older than both partners and learn approximately when it dates from.",
    proof: "Submit a photo of both partners with the item and explain its age or date in the caption.",
    points: 10,
    startDate: "2026-09-02",
    endDate: "2026-09-05",
  }),
  task({
    week: 1,
    number: 50,
    category: "Bonus: Fun Fact",
    title: "Tell Your Partner's Funniest Story",
    instructions: "With your partner's consent, record yourself sharing a funny story that happened to them. Keep it kind and appropriate for an RA reviewer.",
    proof: "Submit a video no longer than 60 seconds showing both partners.",
    note: "**Judged bonus:** RAs may add **10 bonus PGP Coins** if the story makes them laugh. This is awarded through the review override or a manual bonus, not automatically.",
    points: 20,
    startDate: "2026-09-05",
    endDate: "2026-09-06",
  }),
  task({
    week: 2,
    number: 1,
    category: "Creative",
    title: "Fold an Origami Bird",
    instructions: "Work together to fold one recognisable origami bird from paper.",
    proof: "Submit a photo showing both partners with the finished bird.",
    points: 20,
    startDate: "2026-09-07",
    endDate: "2026-09-08",
  }),
  task({
    week: 2,
    number: 2,
    category: "Creative",
    title: "Make a 30-Second PGPR Advertisement",
    instructions: "Create a playful advertisement promoting PGPR and feature both partners.",
    proof: "Submit the finished video; keep it at or under 30 seconds.",
    points: 30,
    startDate: "2026-09-08",
    endDate: "2026-09-11",
  }),
  task({
    week: 2,
    number: 3,
    category: "Creative",
    title: "Create a GIF Together",
    instructions: "Create a short looping GIF featuring both partners. The upload system does not accept .gif files, so export it as a supported short video or capture clear frames.",
    proof: "Submit the loop as MP4, MOV, or WebM, or submit screenshots showing the sequence.",
    points: 10,
    startDate: "2026-09-07",
    endDate: "2026-09-09",
  }),
  task({
    week: 2,
    number: 4,
    category: "Creative",
    title: "Design a New PGPR Mascot",
    instructions: "Invent and draw a new mascot for PGPR, including a name and one-sentence personality description.",
    proof: "Submit a clear photo of both partners with the finished mascot design and include its name in the caption.",
    points: 30,
    startDate: "2026-09-08",
    endDate: "2026-09-12",
  }),
  task({
    week: 2,
    number: 5,
    category: "Creative",
    title: "Make a PGPR Life Meme",
    instructions: "Create an original, good-natured meme about life in PGPR. Do not target or embarrass an identifiable person.",
    proof: "Submit the completed meme image and include both creators in an optional second photo.",
    points: 20,
    startDate: "2026-09-07",
    endDate: "2026-09-10",
  }),
  task({
    week: 2,
    number: 6,
    category: "Creative",
    title: "Recreate a Childhood Photo",
    instructions: "Choose one partner's childhood photo and recreate the pose, outfit, or setting together as closely as practical.",
    proof: "Submit the childhood reference and the new recreation; both partners must appear in the recreation.",
    points: 20,
    startDate: "2026-09-09",
    endDate: "2026-09-12",
  }),
  task({
    week: 2,
    number: 7,
    category: "Creative",
    title: "Decorate Each Other's Doors",
    instructions: "Create temporary decorations for each other's room doors. Use removable materials only, avoid damage, and follow residence rules.",
    proof: "Submit before-and-after or finished photos showing both partners and both decorated doors.",
    points: 20,
    startDate: "2026-09-09",
    endDate: "2026-09-12",
  }),
  task({
    week: 2,
    number: 8,
    category: "Creative",
    title: "Give a Best Buddy Pair Acceptance Speech",
    instructions: "Pretend you have won 'Best Buddy Pair' and deliver an acceptance speech together.",
    proof: "Submit a video at or under 60 seconds in which both partners participate.",
    points: 20,
    startDate: "2026-09-11",
    endDate: "2026-09-13",
  }),
  task({
    week: 2,
    number: 9,
    category: "Explore",
    title: "Walk to West Coast Park McDonald's for Soft Serve",
    instructions: "Walk together to the McDonald's at West Coast Park and have a soft-serve treat. Use safe pedestrian routes and crossings.",
    proof: "Submit a photo showing both partners, the treat, and a recognisable part of the destination.",
    points: 30,
    startDate: "2026-09-07",
    endDate: "2026-09-09",
  }),
  task({
    week: 2,
    number: 10,
    category: "Explore",
    title: "Jog Around an Unfamiliar Faculty",
    instructions: "Choose an NUS faculty or school unfamiliar to both partners and take a light jog around its public outdoor area. Keep the pace comfortable.",
    proof: "Submit a photo of both partners with the faculty sign plus an optional route screenshot.",
    points: 20,
    startDate: "2026-09-07",
    endDate: "2026-09-10",
  }),
  task({
    week: 2,
    number: 11,
    category: "Explore",
    title: "Visit NUS Museum",
    instructions: "Visit NUS Museum together and explore an exhibition. Follow all museum-access and photography rules.",
    proof: "Submit a permitted photo of both partners inside an exhibition; if indoor photography is prohibited, use an entrance photo plus visit evidence.",
    points: 20,
    startDate: "2026-09-08",
    endDate: "2026-09-11",
  }),
  task({
    week: 2,
    number: 12,
    category: "Explore",
    title: "Visit the F1 Pit Building",
    instructions: "Visit the public area near the F1 Pit Building by Marina Bay Sands together. Stay outside restricted zones and follow local rules.",
    proof: "Submit a photo showing both partners with the pit building clearly visible.",
    points: 30,
    startDate: "2026-09-07",
    endDate: "2026-09-13",
  }),
  task({
    week: 2,
    number: 13,
    category: "Explore",
    title: "Pose With the Merlion",
    instructions: "Visit the Merlion together and take the classic forced-perspective photo as if you are drinking the water.",
    proof: "Submit a photo showing both partners and the Merlion water stream.",
    points: 30,
    startDate: "2026-09-08",
    endDate: "2026-09-13",
  }),
  task({
    week: 2,
    number: 14,
    category: "Explore",
    title: "Find Five NUS Sculptures or Public Artworks",
    instructions: "Explore campus and find five different NUS sculptures or public artworks.",
    proof: "Submit a collage or up to five photos that identify all five works and show both partners at each location.",
    points: 30,
    startDate: "2026-09-08",
    endDate: "2026-09-12",
  }),
  task({
    week: 2,
    number: 15,
    category: "Food",
    title: "Eat at The Terrace",
    instructions: "Visit The Terrace and share a meal there with your partner.",
    proof: "Submit a photo showing both partners, the food, and the location.",
    points: 20,
    startDate: "2026-09-07",
    endDate: "2026-09-09",
  }),
  task({
    week: 2,
    number: 16,
    category: "Food",
    title: "Have Breakfast at Cool Spot",
    instructions: "Have a breakfast set together at Cool Spot.",
    proof: "Submit a photo showing both partners, the breakfast sets, and the location.",
    points: 20,
    startDate: "2026-09-07",
    endDate: "2026-09-09",
  }),
  task({
    week: 2,
    number: 17,
    category: "Food",
    title: "Try Spicy Food Together",
    instructions: "Choose a spicy food both partners are comfortable trying. Respect allergies, dietary needs, and personal limits.",
    proof: "Submit a photo or short reaction video showing both partners and the food.",
    points: 30,
    startDate: "2026-09-08",
    endDate: "2026-09-11",
  }),
  task({
    week: 2,
    number: 18,
    category: "Food",
    title: "Share a Milo Tower",
    instructions: "Share a Milo tower with your partner and avoid unnecessary food waste.",
    proof: "Submit a photo showing both partners, the Milo tower, and the location.",
    points: 20,
    startDate: "2026-09-08",
    endDate: "2026-09-10",
  }),
  task({
    week: 2,
    number: 19,
    category: "Food",
    title: "Visit a Café Outside NUS",
    instructions: "Choose and visit a café outside NUS together.",
    proof: "Submit a photo showing both partners, your order, and a recognisable part of the café.",
    points: 40,
    startDate: "2026-09-10",
    endDate: "2026-09-13",
  }),
  task({
    week: 2,
    number: 20,
    category: "Food",
    title: "Cook a Meal for S$10 or Less",
    instructions: "Plan and cook a dish together using no more than S$10 of purchased ingredients. Basic pantry staples may be excluded if you name them in the caption.",
    proof: "Submit a photo of both partners with the finished dish and a receipt or price breakdown totalling S$10 or less.",
    points: 40,
    startDate: "2026-09-09",
    endDate: "2026-09-13",
  }),
  task({
    week: 2,
    number: 21,
    category: "Food",
    title: "Visit Açaí Truck",
    instructions: "Visit Açaí Truck and have an açaí item together with your partner.",
    proof: "Submit a photo showing both partners, the food, and the location.",
    points: 20,
    startDate: "2026-09-08",
    endDate: "2026-09-11",
  }),
  task({
    week: 2,
    number: 22,
    category: "Food",
    title: "Eat Ice Cream With Chopsticks",
    instructions: "Each partner tries eating ice cream with chopsticks. Keep it hygienic and minimise waste.",
    proof: "Submit a photo or short video showing both partners attempting it.",
    points: 20,
    startDate: "2026-09-09",
    endDate: "2026-09-11",
  }),
  task({
    week: 2,
    number: 23,
    category: "F&S",
    title: "Upcycle an Old Item",
    instructions: "Transform an old or unwanted item into something useful or decorative together. Use tools safely.",
    proof: "Submit before-and-after photos and a short process video or photo showing both partners participating.",
    points: 40,
    startDate: "2026-09-07",
    endDate: "2026-09-13",
  }),
  task({
    week: 2,
    number: 24,
    category: "F&S",
    title: "Take a Greenery Panorama",
    instructions: "Visit a nature park or reserve and create a panorama in which both partners are surrounded by greenery. Stay on marked paths and protect wildlife.",
    proof: "Submit the panorama or a clear exported image showing both partners and the natural setting.",
    points: 40,
    startDate: "2026-09-08",
    endDate: "2026-09-13",
  }),
  task({
    week: 2,
    number: 25,
    category: "F&S",
    title: "Attend Any Interest Group Event",
    instructions: "Attend any official sports, arts, or other interest-group event together and participate respectfully.",
    proof: "Submit a photo of both partners with the event signage, organiser, or activity; get consent before including others.",
    points: 40,
    startDate: "2026-09-07",
    endDate: "2026-09-13",
  }),
  task({
    week: 2,
    number: 26,
    category: "F&S: Community",
    title: "Attend a Cluster Event",
    instructions: "Attend any official PGPR Cluster Event together.",
    proof: "Submit a photo showing both partners with the event signage, host, or activity; get consent before including others.",
    points: 30,
    startDate: "2026-09-07",
    endDate: "2026-09-13",
  }),
  task({
    week: 2,
    number: 27,
    category: "F&S",
    title: "Name 10 Fruits While Doing Jumping Jacks",
    instructions: "Together, name 10 different fruits while performing jumping jacks in a safe, open space. Both partners must participate.",
    proof: "Submit one continuous video showing the jumping jacks and all 10 fruit names.",
    points: 20,
    startDate: "2026-09-08",
    endDate: "2026-09-10",
  }),
  task({
    week: 2,
    number: 28,
    category: "Leisure",
    title: "Tag PGPR in an Instagram Story",
    instructions: "Post a photo featuring both partners to an Instagram Story and tag the official PGPR Instagram account. Both partners must consent to the post.",
    proof: "Submit the story image and a screenshot showing the published tag.",
    points: 10,
    startDate: "2026-09-07",
    endDate: "2026-09-10",
  }),
  task({
    week: 2,
    number: 29,
    category: "Leisure",
    title: "Take a Photo With Two Resident Fellows",
    instructions: "Meet two PGPR Resident Fellows with your partner and ask politely for a group photo.",
    proof: "Submit a photo or collage showing both partners with two consenting Resident Fellows.",
    points: 20,
    startDate: "2026-09-07",
    endDate: "2026-09-13",
  }),
  task({
    week: 2,
    number: 30,
    category: "Leisure",
    title: "Draw R1, R2, or R3 on Strava",
    instructions: "Plan and complete a safe walking or running route together that draws R1, R2, or R3 on Strava. Use pedestrian paths and obey road rules.",
    proof: "Submit a screenshot of the completed Strava route and a photo of both partners from the activity.",
    points: 30,
    startDate: "2026-09-08",
    endDate: "2026-09-13",
  }),
  task({
    week: 2,
    number: 31,
    category: "Leisure",
    title: "Take a Night Walk Around PGPR",
    instructions: "Take a relaxed night walk together around well-lit public areas of PGPR. Stay aware of your surroundings and avoid disturbing residents.",
    proof: "Submit a photo of both partners at a recognisable PGPR location during the walk.",
    points: 10,
    startDate: "2026-09-08",
    endDate: "2026-09-12",
  }),
  task({
    week: 2,
    number: 32,
    category: "Leisure",
    title: "Cook a Local Dish",
    instructions: "Choose a local dish and cook it together, following food-safety and kitchen rules.",
    proof: "Submit a photo of both partners with the finished dish, plus an optional preparation photo.",
    points: 20,
    startDate: "2026-09-09",
    endDate: "2026-09-13",
  }),
  task({
    week: 2,
    number: 33,
    category: "Leisure",
    title: "Film a Day-in-the-Life Vlog",
    instructions: "Film a day-in-the-life vlog together. Edit the highlights into an upload-friendly clip.",
    proof: "Submit a highlight video at or under 60 seconds featuring both partners.",
    points: 30,
    startDate: "2026-09-07",
    endDate: "2026-09-11",
  }),
  task({
    week: 2,
    number: 34,
    category: "Leisure",
    title: "Land a Bottle Flip Each",
    instructions: "Keep trying on a safe, stable surface until both partners successfully land a bottle flip.",
    proof: "Submit one continuous video showing each partner's successful flip.",
    points: 10,
    startDate: "2026-09-07",
    endDate: "2026-09-09",
  }),
  task({
    week: 2,
    number: 35,
    category: "Sports & Exercise",
    title: "Play a Sport at a PGP Facility",
    instructions: "Play any sport together at an appropriate PGP facility. Follow facility rules and use suitable equipment.",
    proof: "Submit a photo or short video showing both partners taking part and the facility.",
    points: 20,
    startDate: "2026-09-07",
    endDate: "2026-09-10",
  }),
  task({
    week: 2,
    number: 36,
    category: "Sports & Exercise",
    title: "Cycle at East Coast Park",
    instructions: "Go cycling together at East Coast Park. Use helmets where available, follow cycling rules, and choose a route suitable for both partners.",
    proof: "Submit a photo of both partners with the bicycles and a recognisable East Coast Park location.",
    points: 40,
    startDate: "2026-09-10",
    endDate: "2026-09-13",
  }),
  task({
    week: 2,
    number: 37,
    category: "Sports & Exercise",
    title: "Trace the D2 Route on Foot",
    instructions: "Walk, jog, or run the full D2 shuttle-bus route together using safe pedestrian paths; do not travel on the road carriageway.",
    proof: "Submit a Strava or equivalent route screenshot covering the full route and a photo of both partners from the activity.",
    points: 40,
    startDate: "2026-09-09",
    endDate: "2026-09-13",
  }),
  task({
    week: 2,
    number: 38,
    category: "Multi-pair",
    title: "Write a Meaningful Card for Your Partner",
    instructions: "Each partner writes a sincere card for the other and exchanges it. This is a normal two-person-team challenge despite its spreadsheet category.",
    proof: "Submit a photo showing both partners with the two cards; private message text may be covered.",
    points: 10,
    startDate: "2026-09-11",
    endDate: "2026-09-13",
  }),
  task({
    week: 2,
    number: 39,
    category: "Multi-pair",
    title: "Catch the Sunrise Together",
    instructions: "Watch the sunrise together from a safe public location and enjoy the golden hour. This is a normal two-person-team challenge despite its spreadsheet category.",
    proof: "Submit a photo showing both partners and the sunrise or golden-hour sky.",
    points: 20,
    startDate: "2026-09-09",
    endDate: "2026-09-12",
  }),
  task({
    week: 2,
    number: 40,
    category: "Multi-pair",
    title: "Race Another Team",
    instructions: "Form a two-team group and hold a friendly race in a safe, open area. Agree on an accessible distance and format for everyone; do not race on roads.",
    proof: "Submit one shared video showing all four residents and the start and finish of the race.",
    points: 30,
    startDate: "2026-09-11",
    endDate: "2026-09-13",
    groupTeams: 2,
  }),
  task({
    week: 2,
    number: 41,
    category: "Multi-pair",
    title: "Picnic at Marina Barrage With Three Teams",
    instructions: "Form a three-team group and have a picnic together at Marina Barrage. Leave the area clean when you finish.",
    proof: "Submit one shared photo showing all six residents, the picnic, and Marina Barrage.",
    points: 30,
    startDate: "2026-09-10",
    endDate: "2026-09-13",
    groupTeams: 3,
  }),
  task({
    week: 2,
    number: 42,
    category: "Multi-pair",
    title: "Host a Three-Team Potluck",
    instructions: "Form a three-team group and host a potluck in a permitted space. Check allergies and dietary restrictions, and follow residence rules. Extra guests may join, but the shared submission and coins belong to the three linked teams.",
    proof: "Submit one shared photo showing all six residents and the contributed food.",
    points: 50,
    startDate: "2026-09-10",
    endDate: "2026-09-13",
    groupTeams: 3,
  }),
  task({
    week: 2,
    number: 43,
    category: "Multi-pair",
    title: "Organise a Three-Team Study Session",
    instructions: "Form a three-team group and hold a focused study session together in a suitable space. Respect quiet-zone rules.",
    proof: "Submit one shared photo showing all six residents, study materials, and the session setting.",
    points: 30,
    startDate: "2026-09-08",
    endDate: "2026-09-12",
    groupTeams: 3,
  }),
  task({
    week: 2,
    number: 44,
    category: "Multi-pair",
    title: "Film a TikTok With Another Team",
    instructions: "Form a two-team group and create a TikTok-style dance or challenge video together. Choose safe, respectful content.",
    proof: "Submit one shared video at or under 60 seconds showing all four residents.",
    points: 30,
    startDate: "2026-09-10",
    endDate: "2026-09-13",
    groupTeams: 2,
  }),
  task({
    week: 2,
    number: 45,
    category: "Pokémon",
    title: "Visit the PGPR House Logo",
    instructions: "Find the PGPR House logo in the main foyer and visit it together.",
    proof: "Submit a photo showing both partners and the full logo.",
    points: 10,
    startDate: "2026-09-07",
    endDate: "2026-09-09",
  }),
  task({
    week: 2,
    number: 46,
    category: "Pokémon",
    title: "Take a Photo With the PGPR Hostel Master",
    instructions: "Meet the PGPR Hostel Master with your partner and politely ask for a photo. Do not interrupt official duties.",
    proof: "Submit a photo showing both partners and the consenting Hostel Master.",
    points: 10,
    startDate: "2026-09-07",
    endDate: "2026-09-13",
  }),
  task({
    week: 2,
    number: 47,
    category: "Pokémon",
    title: "Take a Photo With a PGPR RLO",
    instructions: "Meet any PGPR Residential Life Officer with your partner and politely ask for a photo. Do not interrupt official duties.",
    proof: "Submit a photo showing both partners and the consenting RLO.",
    points: 10,
    startDate: "2026-09-07",
    endDate: "2026-09-13",
  }),
  task({
    week: 2,
    number: 48,
    category: "Bonus",
    title: "Hike at MacRitchie Reservoir",
    instructions: "Take a hike together at MacRitchie Reservoir. Stay on marked trails, carry water, and turn back if weather or health conditions are unsafe.",
    proof: "Submit a photo showing both partners with a MacRitchie sign and an optional route screenshot.",
    points: 50,
    startDate: "2026-09-11",
    endDate: "2026-09-13",
  }),
  task({
    week: 2,
    number: 49,
    category: "Bonus",
    title: "Create a Five-Minute PGPals Recap Film",
    instructions: "Create a five-minute cinematic recap of your PGPals journey. Because each uploaded video is limited to 60 seconds, upload a trailer or excerpt and place a viewable link to the full five-minute film in the caption.",
    proof: "Submit a trailer at or under 60 seconds plus at least one journey photo, and include the full-film link in the caption.",
    points: 50,
    startDate: "2026-09-11",
    endDate: "2026-09-13",
  }),
  task({
    week: 2,
    number: 50,
    category: "Bonus",
    title: "Write a Song for Your Pair",
    instructions: "Write and perform an original song inspired by your pair or PGPals experience. Both partners should contribute to the writing or performance.",
    proof: "Submit a video excerpt at or under 60 seconds and include the song title and both partners' contributions in the caption.",
    points: 30,
    startDate: "2026-09-09",
    endDate: "2026-09-13",
  }),
];

export function validateFinalEventData() {
  const errors: string[] = [];
  const expectedCounts = new Map<1 | 2, number>([
    [1, 50],
    [2, 50],
  ]);

  for (const [week, expected] of expectedCounts) {
    const tasks = FINAL_TASKS.filter((item) => item.week === week);
    if (tasks.length !== expected) {
      errors.push(`Week ${week} must contain ${expected} tasks; found ${tasks.length}.`);
    }
    const numbers = new Set(tasks.map((item) => item.number));
    for (let number = 1; number <= expected; number += 1) {
      if (!numbers.has(number)) errors.push(`Week ${week} is missing challenge ${number}.`);
    }
  }

  const keys = new Set<string>();
  for (const item of FINAL_TASKS) {
    const key = `${item.week}:${item.number}`;
    if (keys.has(key)) errors.push(`Duplicate challenge key ${key}.`);
    keys.add(key);
    if (!item.title.trim() || !item.description.trim()) {
      errors.push(`${key} needs a title and description.`);
    }
    if (!Number.isInteger(item.points) || item.points < 0) {
      errors.push(`${key} has invalid points.`);
    }
    const releaseAt = Date.parse(`${item.startDate}T00:00:00+08:00`);
    const deadlineAt = Date.parse(`${item.endDate}T23:59:00+08:00`);
    if (!Number.isFinite(releaseAt) || !Number.isFinite(deadlineAt) || deadlineAt <= releaseAt) {
      errors.push(`${key} has invalid dates.`);
    }
    if (item.type === "pair" && (item.pairTeamCount < 2 || item.pairTeamCount > 20)) {
      errors.push(`${key} has invalid group size ${item.pairTeamCount}.`);
    }
    if (item.type === "standard" && item.pairTeamCount !== 2) {
      errors.push(`${key} must use the standard pair-team-count default.`);
    }
  }

  const emails = [...FINAL_RA_ACCOUNTS.map((ra) => ra.email), SHARED_ADMIN_EMAIL];
  if (new Set(emails).size !== emails.length) errors.push("Admin emails must be unique.");
  if (emails.some((email) => email !== email.toLowerCase())) {
    errors.push("Admin emails must be lowercase.");
  }

  if (errors.length > 0) throw new Error(errors.join("\n"));
}
